### ISSUE TITLE
Cannot hot reload

### ISSUE THREAD

**Issue by Tangent-90** [slaveOftime/Fun.Blazor#41] opened 2022-12-13 15:43 UTC
![图片](https://user-images.githubusercontent.com/43789618/207377514-d0f71c18-db36-4acf-ac36-05c16bf339ea.png)

Reproduce Procedure
1. `dotnet new fb-mix -o Tfbm`
2. `dotnet run .\Tfbm.Server\Tfbm.Server.fsproj`
3. `fun-blazor watch .\Tfbm.Wasm\Tfbm.Wasm.fsproj`
4. modify a component and save

**Comment by albertwoo** [comment] 2022-12-16 01:11
Which version are you using? There is a fsharp compiler service bug related to this issue if you are using dotnet 7. Not just for your project but also for the Fun.Blazor.Cli, so it is better to install the cli locally with your project to fix the version to dotnet 6 by create a globaljson file.

**Comment by Tangent-90** [comment] 2022-12-19 12:13
I have test it in dotnet 6, and it works fine, but dotnet 7 will failed. Will you fix it?

**Comment by albertwoo** [comment] 2022-12-20 09:03
Sure, I will fix it. But the root cause is in package FSharp.Compiler.Service which has a bug if used in dotnet 7. When they fix it, I will fix it accordingly.

**Comment by boyedarat** [comment] 2023-01-24 04:27
Has this been addressed in the latest v3 betas?

**Comment by albertwoo** [comment] 2023-01-24 08:39
Not yet. https://github.com/dotnet/fsharp/issues/14289#issuecomment-1312623293
Did not see any progress.

**Comment by Tangent-90** [comment] 2023-03-24 15:15
can fix by adding a target to `Microsoft.FSharp.targets`

https://github.com/dotnet/fsharp/issues/14250

**Comment by albertwoo** [comment] 2023-03-25 03:14
@Tangent-90 thanks for the discovery, I will verify that and update the docs accordingly. This issue is blocking me to release 3.0.0 for so long.

**Comment by albertwoo** [comment] 2023-03-27 02:25
Strange, it still does not work for me.

**Comment by Tangent-90** [comment] 2023-03-27 02:46
> Strange, it still does not work for me.

which `Microsoft.FSharp.Targets` did you edit? It should be under dotnet folder, not VS.

**Comment by albertwoo** [comment] 2023-03-27 02:59
You mean this file "C:\Program Files\dotnet\sdk\7.0.200\FSharp\Microsoft.FSharp.Targets" ?

**Comment by Tangent-90** [comment] 2023-03-27 03:00
> You mean this file "C:\Program Files\dotnet\sdk\7.0.200\FSharp\Microsoft.FSharp.Targets" ?

yes

**Comment by albertwoo** [comment] 2023-03-27 03:48
Still not work for me. Can you share the detail steps for this?

**Comment by Tangent-90** [comment] 2023-03-27 12:24
> Still not work for me. Can you share the detail steps for this?

![图片](https://user-images.githubusercontent.com/43789618/227940640-70312129-3daf-46b2-9b46-1fdc94acf12f.png)

Just paste it before `CoreCompile`, and save, and run `fun-blazor watch`

**Comment by albertwoo** [comment] 2023-03-28 02:40
Thanks, it works now.

**Comment by sritharans** [comment] 2023-04-05 04:30
@albertwoo Could you also update the v3 release with fun-blazor for .Net 7?

**Comment by albertwoo** [comment] 2023-04-06 00:26
Upgrade fun-blazor to dotnet 7 will not solve this issue. And it should work if you are using dotnet 7 with the workaround.

I also updated the documents and default templates to add this workaround for them.
We can actually add below stuff to the projects you want to support hot-reload if people do not want to touch the global targets file:
```xml
<Target Name="ShimReferencePathsWhenCommonTargetsDoesNotUnderstandReferenceAssemblies"
    BeforeTargets="CoreCompile"
    Condition="'@(ReferencePathWithRefAssemblies)' == ''">
    <ItemGroup>
        <ReferencePathWithRefAssemblies Include="@(ReferencePath)" />
    </ItemGroup>
</Target>
```

**Closed by albertwoo** 2023-04-06 00:26 UTC

**Comment by boyedarat** [comment] 2023-04-15 14:31
@albertwoo This is the error I get when I run fun-blazor:
```
C:\Users\st4r>dotnet tool install -g Fun.Blazor.Cli
You can invoke the tool using the following command: fun-blazor
Tool 'fun.blazor.cli' (version '3.0.0') was successfully installed.

C:\Users\st4r>fun-blazor
You must install or update .NET to run this application.

App: C:\Users\st4r\.dotnet\tools\fun-blazor.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  7.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64
```
I can't install .Net 6.0 runtime on this system, cause some conflict with an app that also uses the .Net runtime.

**Comment by albertwoo** [comment] 2023-04-17 05:04
@boyedarat I thought it should be compatible with higher version of dotnet SDK.

Add added one 7.0 as the target in the new version 3.0.1, please try if it works.

**Comment by boyedarat** [comment] 2023-04-28 00:54
> @boyedarat I thought it should be compatible with higher version of dotnet SDK.
> 
> Add added one 7.0 as the target in the new version 3.0.1, please try if it works.

Thanks, much appreciated. It works with fb-mix.
Still testing it out with the other templates.

Will submit an issue if I run into further problems.
